### ISSUE TITLE
stop not working

### ISSUE THREAD

**Issue by codeSupreme** [ipedro/PAGestureAssistant#4]
after calling stopGestureAssistant the assistant starts back up.  How do I stop/kill the assistant indefinitely?

**Comment by ipedro** [comment]
Apparently there's an issue preventing the stop from occurring if the assistant is presenting at the time. Will look into it!

**Comment by ipedro** [comment]
Fixed in `0.2.7`.

 `- (void)stopGestureAssistant` now always works as expected
