### ISSUE TITLE
Combined modes

### ISSUE THREAD

**Issue by 8masterofpuppets8** [ipedro/PAGestureAssistant#5]
Hey guys, great library first of all! I was wondering if there's a way to combine both tutorial modes? For example, I would like to be in Tutorial mode but the user interaction to be active while user is being prompted to do an action. I cannot use the Assistant mode because the action is repeated due to the timer but I need it to happen only once..

Any info on this would be greatly appreciated!

**Comment by ipedro** [comment]
Thanks for the compliment! You could schedule the assistant without a completion block (assistant mode), and in your button/control's action handler call one of the stop methods. I think that might be the behavior you want.

```obj-c
- (void)stopGestureAssistant;
- (void)stopGestureAssistantWithCompletion:(PAGestureCompletion)completion;
```

**Comment by 8masterofpuppets8** [comment]
Yeah that's what I ended up doing and it seems to work very well. Thanks for the reply!

**Comment by ipedro** [comment]
Nice!
