### ISSUE TITLE
Making a transparency & subviews access

### ISSUE THREAD

**Issue by praveenkumar56060** [ipedro/PAGestureAssistant#6]
Hi,

Thanks for the awesome library. I've one requirement. When,  we are not assigning `setTapImage` it creates a circle as `tapColor` how to make that place itself transparency.

Means, on that certain point it should be transparency even, `backgroundView` colour also shouldn't affect.

 And, how to add buttons and handle its callback on certain viewcontrollers?

**Comment by praveenkumar56060** [comment]
For, additional information.

I can make circle transparency on certain view object using below code snippet.

	CGContextRef context = UIGraphicsGetCurrentContext();

	CGContextSetFillColorWithColor( context, [UIColor blueColor].CGColor );
	CGContextFillRect( context, rect );

	CGRect holeRectIntersection = CGRectIntersection( CGRectMake(50, 50, 50, 50), rect );

	if( CGRectIntersectsRect( holeRectIntersection, rect ) )
	{
	    CGContextAddEllipseInRect(context, holeRectIntersection);
	    CGContextClip(context);
	    CGContextClearRect(context, holeRectIntersection);
	    CGContextSetFillColorWithColor( context, [UIColor clearColor].CGColor );
	    CGContextFillRect( context, holeRectIntersection);
	}

[Code Reference](http://stackoverflow.com/a/15810458/940096)

How do we integrate this in this library?

**Comment by ipedro** [comment]
Hi Praveenkumar, I'm not sure if I understood exactly what you want, but you could pass a color with transparency. 

Example
```
tapColor = [UIColor colorWithRed:197.0/255.0 
                        green:169.0/255.0 
                         blue:140.0/255.0 
                        alpha:1.0];

```

**Comment by praveenkumar56060** [comment]
Thanks for your comment. Anyway, i've achieved it by setting a `image` option through `PAGestureView`
