### ISSUE TITLE
Custom Control access.

### ISSUE THREAD

**Issue by praveenkumar56060** [ipedro/PAGestureAssistant#7]
Hi,

I am trying to add a skip button. And, i want to stop the tutorials if skip pressed on a certain controllers. How to add custom controls (Like Buttons) and get access where tutorial shows?

**Comment by ipedro** [comment]
That isn't supported, sorry.

**Comment by praveenkumar56060** [comment]
Thanks anyway! Found other ways to implement same in this lib.
